apiVersion: v2
name: auth-api
description: Authentication and Identity Management Service
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - auth
  - jwt
  - microservice
maintainers:
  - name: Digital Bank Team
