apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth-api.fullname" . }}-secret
  labels:
    {{- include "auth-api.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ .Values.secrets.JWT_SECRET | b64enc | quote }}
  database-url: {{ .Values.secrets.DATABASE_URL | b64enc | quote }}
